apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: predicted-object-raw-frame-topic-1
  labels:
    strimzi.io/cluster: kafka2
spec:
  partitions: 352
  replicas: 1
  #config:
  # retention.ms: 100000
  # max.message.bytes: 30000000
