apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: testpico-3
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 50
  replicas: 2
  config:
    retention.ms: 10000
    segment.bytes: 1073741824
