apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: testpico-1
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 10000
    segment.bytes: 10737418240
