apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-manager
  name: kafka-manager
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kafka-manager
    spec:
      containers:
      - env:
        - name: APPLICATION_SECRET
          value: letmein
        - name: JMX_PORT
          value: "9181"
        - name: ZK_HOSTS
          value: zk-1:2181,zk-2:2181,zk-3:2181
        image: sheepkiller/kafka-manager
        name: kafka-manager
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
status: {}
