apiVersion: v1
data:
  KAFKA_DEFAULT_REPLICATION_FACTOR: "3"
  KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  KAFKA_JMX_PORT: "9181"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
  KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:9192
  KAFKA_ZOOKEEPER_CONNECT: zk-1:2181,zk-2:2181,zk-3:2181
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-3-kafka-common-env
  name: kafka-3-kafka-common-env
