apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-1
  name: kafka-1
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kafka-1
    spec:
      containers:
      - env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: INTERNAL://kafka-1:9192,EXTERNAL://10.146.0.2:9092
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          valueFrom:
            configMapKeyRef:
              key: KAFKA_DEFAULT_REPLICATION_FACTOR
              name: kafka-1-kafka-common-env
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          valueFrom:
            configMapKeyRef:
              key: KAFKA_INTER_BROKER_LISTENER_NAME
              name: kafka-1-kafka-common-env
        - name: KAFKA_JMX_HOSTNAME
          value: kafka-1
        - name: KAFKA_JMX_PORT
          valueFrom:
            configMapKeyRef:
              key: KAFKA_JMX_PORT
              name: kafka-1-kafka-common-env
        - name: KAFKA_LISTENERS
          valueFrom:
            configMapKeyRef:
              key: KAFKA_LISTENERS
              name: kafka-1-kafka-common-env
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          valueFrom:
            configMapKeyRef:
              key: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              name: kafka-1-kafka-common-env
        - name: KAFKA_ZOOKEEPER_CONNECT
          valueFrom:
            configMapKeyRef:
              key: KAFKA_ZOOKEEPER_CONNECT
              name: kafka-1-kafka-common-env
        image: confluentinc/cp-kafka:4.0.0
        name: kafka-1
        ports:
        - containerPort: 9092
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/kafka/data
          name: kafka-1
      restartPolicy: Always
      volumes:
      - name: kafka-1
        persistentVolumeClaim:
          claimName: kafka-1
status: {}
