apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-2
  name: kafka-2
spec:
  ports:
  - name: "9093"
    port: 9093
    targetPort: 9092
  selector:
    io.kompose.service: kafka-2
status:
  loadBalancer: {}
