apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: zk-2
  name: zk-2
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: zk-2
    spec:
      containers:
      - env:
        - name: ZOOKEEPER_CLIENT_PORT
          valueFrom:
            configMapKeyRef:
              key: ZOOKEEPER_CLIENT_PORT
              name: zk-2-zk-common-env
        - name: ZOOKEEPER_SERVERS
          value: zk-1:2888:3888;0.0.0.0:2888:3888;zk-3:2888:3888
        - name: ZOOKEEPER_SERVER_ID
          value: "2"
        image: confluentinc/cp-zookeeper:4.0.0
        name: zk-2
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/zookeeper/data
          name: zk-2
      restartPolicy: Always
      volumes:
      - name: zk-2
        persistentVolumeClaim:
          claimName: zk-2
status: {}
